services:
  azure-write:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azure-write
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - eh-emulator
  eventhubs-emulator:
    image: mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest
    container_name: eventhubs-emulator
    ports:
      - "5672:5672"
      - "9092:9092"
      - "5300:5300"
    environment:
      ACCEPT_EULA: Y
      BLOB_SERVER: azure-write
      METADATA_SERVER: azure-write
    depends_on:
      - azure-write
    networks:
      - eh-emulator
    volumes:
      - ./config.json:/Eventhubs_Emulator/ConfigFiles/Config.json
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "AdminPassword123!"  # Replace with a strong password
    restart: unless-stopped
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: eventhubs-emulator
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: eventhubs-emulator:9093
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="$ConnectionString"
        password="Endpoint=sb://eventhubs-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;";
    networks:
      - eh-emulator

networks:
  eh-emulator:
    name: eh-emulator
